// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoginRepository creates a new instance of MockLoginRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginRepository {
	mock := &MockLoginRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginRepository is an autogenerated mock type for the LoginRepository type
type MockLoginRepository struct {
	mock.Mock
}

type MockLoginRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginRepository) EXPECT() *MockLoginRepository_Expecter {
	return &MockLoginRepository_Expecter{mock: &_m.Mock}
}

// CountDailyUniqueUsers provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) CountDailyUniqueUsers(ctx context.Context, date string) (int, error) {
	ret := _mock.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for CountDailyUniqueUsers")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, date)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginRepository_CountDailyUniqueUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountDailyUniqueUsers'
type MockLoginRepository_CountDailyUniqueUsers_Call struct {
	*mock.Call
}

// CountDailyUniqueUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - date string
func (_e *MockLoginRepository_Expecter) CountDailyUniqueUsers(ctx interface{}, date interface{}) *MockLoginRepository_CountDailyUniqueUsers_Call {
	return &MockLoginRepository_CountDailyUniqueUsers_Call{Call: _e.mock.On("CountDailyUniqueUsers", ctx, date)}
}

func (_c *MockLoginRepository_CountDailyUniqueUsers_Call) Run(run func(ctx context.Context, date string)) *MockLoginRepository_CountDailyUniqueUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginRepository_CountDailyUniqueUsers_Call) Return(n int, err error) *MockLoginRepository_CountDailyUniqueUsers_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLoginRepository_CountDailyUniqueUsers_Call) RunAndReturn(run func(ctx context.Context, date string) (int, error)) *MockLoginRepository_CountDailyUniqueUsers_Call {
	_c.Call.Return(run)
	return _c
}

// CountMonthlyUniqueUsers provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) CountMonthlyUniqueUsers(ctx context.Context, month string) (int, error) {
	ret := _mock.Called(ctx, month)

	if len(ret) == 0 {
		panic("no return value specified for CountMonthlyUniqueUsers")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, month)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, month)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, month)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginRepository_CountMonthlyUniqueUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMonthlyUniqueUsers'
type MockLoginRepository_CountMonthlyUniqueUsers_Call struct {
	*mock.Call
}

// CountMonthlyUniqueUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - month string
func (_e *MockLoginRepository_Expecter) CountMonthlyUniqueUsers(ctx interface{}, month interface{}) *MockLoginRepository_CountMonthlyUniqueUsers_Call {
	return &MockLoginRepository_CountMonthlyUniqueUsers_Call{Call: _e.mock.On("CountMonthlyUniqueUsers", ctx, month)}
}

func (_c *MockLoginRepository_CountMonthlyUniqueUsers_Call) Run(run func(ctx context.Context, month string)) *MockLoginRepository_CountMonthlyUniqueUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginRepository_CountMonthlyUniqueUsers_Call) Return(n int, err error) *MockLoginRepository_CountMonthlyUniqueUsers_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLoginRepository_CountMonthlyUniqueUsers_Call) RunAndReturn(run func(ctx context.Context, month string) (int, error)) *MockLoginRepository_CountMonthlyUniqueUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RecordLoginTx provides a mock function for the type MockLoginRepository
func (_mock *MockLoginRepository) RecordLoginTx(ctx context.Context, userID uuid.UUID, loginTime time.Time) error {
	ret := _mock.Called(ctx, userID, loginTime)

	if len(ret) == 0 {
		panic("no return value specified for RecordLoginTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, loginTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginRepository_RecordLoginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordLoginTx'
type MockLoginRepository_RecordLoginTx_Call struct {
	*mock.Call
}

// RecordLoginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - loginTime time.Time
func (_e *MockLoginRepository_Expecter) RecordLoginTx(ctx interface{}, userID interface{}, loginTime interface{}) *MockLoginRepository_RecordLoginTx_Call {
	return &MockLoginRepository_RecordLoginTx_Call{Call: _e.mock.On("RecordLoginTx", ctx, userID, loginTime)}
}

func (_c *MockLoginRepository_RecordLoginTx_Call) Run(run func(ctx context.Context, userID uuid.UUID, loginTime time.Time)) *MockLoginRepository_RecordLoginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoginRepository_RecordLoginTx_Call) Return(err error) *MockLoginRepository_RecordLoginTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginRepository_RecordLoginTx_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, loginTime time.Time) error) *MockLoginRepository_RecordLoginTx_Call {
	_c.Call.Return(run)
	return _c
}
