// Code generated by ent, DO NOT EDIT.

package monthlyuniqueuser

import (
	"entgo.io/ent/dialect/sql"
	"github.com/choonhong/user-analytics/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldLTE(FieldID, id))
}

// Month applies equality check predicate on the "month" field. It's identical to MonthEQ.
func Month(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldEQ(FieldMonth, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldEQ(FieldUserID, v))
}

// MonthEQ applies the EQ predicate on the "month" field.
func MonthEQ(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldEQ(FieldMonth, v))
}

// MonthNEQ applies the NEQ predicate on the "month" field.
func MonthNEQ(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldNEQ(FieldMonth, v))
}

// MonthIn applies the In predicate on the "month" field.
func MonthIn(vs ...string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldIn(FieldMonth, vs...))
}

// MonthNotIn applies the NotIn predicate on the "month" field.
func MonthNotIn(vs ...string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldNotIn(FieldMonth, vs...))
}

// MonthGT applies the GT predicate on the "month" field.
func MonthGT(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldGT(FieldMonth, v))
}

// MonthGTE applies the GTE predicate on the "month" field.
func MonthGTE(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldGTE(FieldMonth, v))
}

// MonthLT applies the LT predicate on the "month" field.
func MonthLT(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldLT(FieldMonth, v))
}

// MonthLTE applies the LTE predicate on the "month" field.
func MonthLTE(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldLTE(FieldMonth, v))
}

// MonthContains applies the Contains predicate on the "month" field.
func MonthContains(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldContains(FieldMonth, v))
}

// MonthHasPrefix applies the HasPrefix predicate on the "month" field.
func MonthHasPrefix(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldHasPrefix(FieldMonth, v))
}

// MonthHasSuffix applies the HasSuffix predicate on the "month" field.
func MonthHasSuffix(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldHasSuffix(FieldMonth, v))
}

// MonthEqualFold applies the EqualFold predicate on the "month" field.
func MonthEqualFold(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldEqualFold(FieldMonth, v))
}

// MonthContainsFold applies the ContainsFold predicate on the "month" field.
func MonthContainsFold(v string) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldContainsFold(FieldMonth, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.FieldLTE(FieldUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MonthlyUniqueUser) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MonthlyUniqueUser) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MonthlyUniqueUser) predicate.MonthlyUniqueUser {
	return predicate.MonthlyUniqueUser(sql.NotPredicates(p))
}
