// Code generated by ent, DO NOT EDIT.

package dailyuniqueuser

import (
	"entgo.io/ent/dialect/sql"
	"github.com/choonhong/user-analytics/db/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldLTE(FieldID, id))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldEQ(FieldDate, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldEQ(FieldUserID, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldLTE(FieldDate, v))
}

// DateContains applies the Contains predicate on the "date" field.
func DateContains(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldContains(FieldDate, v))
}

// DateHasPrefix applies the HasPrefix predicate on the "date" field.
func DateHasPrefix(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldHasPrefix(FieldDate, v))
}

// DateHasSuffix applies the HasSuffix predicate on the "date" field.
func DateHasSuffix(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldHasSuffix(FieldDate, v))
}

// DateEqualFold applies the EqualFold predicate on the "date" field.
func DateEqualFold(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldEqualFold(FieldDate, v))
}

// DateContainsFold applies the ContainsFold predicate on the "date" field.
func DateContainsFold(v string) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldContainsFold(FieldDate, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.FieldLTE(FieldUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyUniqueUser) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyUniqueUser) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyUniqueUser) predicate.DailyUniqueUser {
	return predicate.DailyUniqueUser(sql.NotPredicates(p))
}
