// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/choonhong/user-analytics/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/choonhong/user-analytics/ent/dailyuniqueuser"
	"github.com/choonhong/user-analytics/ent/monthlyuniqueuser"
	"github.com/choonhong/user-analytics/ent/userlogin"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DailyUniqueUser is the client for interacting with the DailyUniqueUser builders.
	DailyUniqueUser *DailyUniqueUserClient
	// MonthlyUniqueUser is the client for interacting with the MonthlyUniqueUser builders.
	MonthlyUniqueUser *MonthlyUniqueUserClient
	// UserLogin is the client for interacting with the UserLogin builders.
	UserLogin *UserLoginClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DailyUniqueUser = NewDailyUniqueUserClient(c.config)
	c.MonthlyUniqueUser = NewMonthlyUniqueUserClient(c.config)
	c.UserLogin = NewUserLoginClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		DailyUniqueUser:   NewDailyUniqueUserClient(cfg),
		MonthlyUniqueUser: NewMonthlyUniqueUserClient(cfg),
		UserLogin:         NewUserLoginClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		DailyUniqueUser:   NewDailyUniqueUserClient(cfg),
		MonthlyUniqueUser: NewMonthlyUniqueUserClient(cfg),
		UserLogin:         NewUserLoginClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DailyUniqueUser.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DailyUniqueUser.Use(hooks...)
	c.MonthlyUniqueUser.Use(hooks...)
	c.UserLogin.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.DailyUniqueUser.Intercept(interceptors...)
	c.MonthlyUniqueUser.Intercept(interceptors...)
	c.UserLogin.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DailyUniqueUserMutation:
		return c.DailyUniqueUser.mutate(ctx, m)
	case *MonthlyUniqueUserMutation:
		return c.MonthlyUniqueUser.mutate(ctx, m)
	case *UserLoginMutation:
		return c.UserLogin.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DailyUniqueUserClient is a client for the DailyUniqueUser schema.
type DailyUniqueUserClient struct {
	config
}

// NewDailyUniqueUserClient returns a client for the DailyUniqueUser from the given config.
func NewDailyUniqueUserClient(c config) *DailyUniqueUserClient {
	return &DailyUniqueUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dailyuniqueuser.Hooks(f(g(h())))`.
func (c *DailyUniqueUserClient) Use(hooks ...Hook) {
	c.hooks.DailyUniqueUser = append(c.hooks.DailyUniqueUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dailyuniqueuser.Intercept(f(g(h())))`.
func (c *DailyUniqueUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.DailyUniqueUser = append(c.inters.DailyUniqueUser, interceptors...)
}

// Create returns a builder for creating a DailyUniqueUser entity.
func (c *DailyUniqueUserClient) Create() *DailyUniqueUserCreate {
	mutation := newDailyUniqueUserMutation(c.config, OpCreate)
	return &DailyUniqueUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DailyUniqueUser entities.
func (c *DailyUniqueUserClient) CreateBulk(builders ...*DailyUniqueUserCreate) *DailyUniqueUserCreateBulk {
	return &DailyUniqueUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DailyUniqueUserClient) MapCreateBulk(slice any, setFunc func(*DailyUniqueUserCreate, int)) *DailyUniqueUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DailyUniqueUserCreateBulk{err: fmt.Errorf("calling to DailyUniqueUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DailyUniqueUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DailyUniqueUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DailyUniqueUser.
func (c *DailyUniqueUserClient) Update() *DailyUniqueUserUpdate {
	mutation := newDailyUniqueUserMutation(c.config, OpUpdate)
	return &DailyUniqueUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DailyUniqueUserClient) UpdateOne(_m *DailyUniqueUser) *DailyUniqueUserUpdateOne {
	mutation := newDailyUniqueUserMutation(c.config, OpUpdateOne, withDailyUniqueUser(_m))
	return &DailyUniqueUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DailyUniqueUserClient) UpdateOneID(id int) *DailyUniqueUserUpdateOne {
	mutation := newDailyUniqueUserMutation(c.config, OpUpdateOne, withDailyUniqueUserID(id))
	return &DailyUniqueUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DailyUniqueUser.
func (c *DailyUniqueUserClient) Delete() *DailyUniqueUserDelete {
	mutation := newDailyUniqueUserMutation(c.config, OpDelete)
	return &DailyUniqueUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DailyUniqueUserClient) DeleteOne(_m *DailyUniqueUser) *DailyUniqueUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DailyUniqueUserClient) DeleteOneID(id int) *DailyUniqueUserDeleteOne {
	builder := c.Delete().Where(dailyuniqueuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DailyUniqueUserDeleteOne{builder}
}

// Query returns a query builder for DailyUniqueUser.
func (c *DailyUniqueUserClient) Query() *DailyUniqueUserQuery {
	return &DailyUniqueUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDailyUniqueUser},
		inters: c.Interceptors(),
	}
}

// Get returns a DailyUniqueUser entity by its id.
func (c *DailyUniqueUserClient) Get(ctx context.Context, id int) (*DailyUniqueUser, error) {
	return c.Query().Where(dailyuniqueuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DailyUniqueUserClient) GetX(ctx context.Context, id int) *DailyUniqueUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DailyUniqueUserClient) Hooks() []Hook {
	return c.hooks.DailyUniqueUser
}

// Interceptors returns the client interceptors.
func (c *DailyUniqueUserClient) Interceptors() []Interceptor {
	return c.inters.DailyUniqueUser
}

func (c *DailyUniqueUserClient) mutate(ctx context.Context, m *DailyUniqueUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DailyUniqueUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DailyUniqueUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DailyUniqueUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DailyUniqueUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DailyUniqueUser mutation op: %q", m.Op())
	}
}

// MonthlyUniqueUserClient is a client for the MonthlyUniqueUser schema.
type MonthlyUniqueUserClient struct {
	config
}

// NewMonthlyUniqueUserClient returns a client for the MonthlyUniqueUser from the given config.
func NewMonthlyUniqueUserClient(c config) *MonthlyUniqueUserClient {
	return &MonthlyUniqueUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `monthlyuniqueuser.Hooks(f(g(h())))`.
func (c *MonthlyUniqueUserClient) Use(hooks ...Hook) {
	c.hooks.MonthlyUniqueUser = append(c.hooks.MonthlyUniqueUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `monthlyuniqueuser.Intercept(f(g(h())))`.
func (c *MonthlyUniqueUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.MonthlyUniqueUser = append(c.inters.MonthlyUniqueUser, interceptors...)
}

// Create returns a builder for creating a MonthlyUniqueUser entity.
func (c *MonthlyUniqueUserClient) Create() *MonthlyUniqueUserCreate {
	mutation := newMonthlyUniqueUserMutation(c.config, OpCreate)
	return &MonthlyUniqueUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MonthlyUniqueUser entities.
func (c *MonthlyUniqueUserClient) CreateBulk(builders ...*MonthlyUniqueUserCreate) *MonthlyUniqueUserCreateBulk {
	return &MonthlyUniqueUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MonthlyUniqueUserClient) MapCreateBulk(slice any, setFunc func(*MonthlyUniqueUserCreate, int)) *MonthlyUniqueUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MonthlyUniqueUserCreateBulk{err: fmt.Errorf("calling to MonthlyUniqueUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MonthlyUniqueUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MonthlyUniqueUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MonthlyUniqueUser.
func (c *MonthlyUniqueUserClient) Update() *MonthlyUniqueUserUpdate {
	mutation := newMonthlyUniqueUserMutation(c.config, OpUpdate)
	return &MonthlyUniqueUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MonthlyUniqueUserClient) UpdateOne(_m *MonthlyUniqueUser) *MonthlyUniqueUserUpdateOne {
	mutation := newMonthlyUniqueUserMutation(c.config, OpUpdateOne, withMonthlyUniqueUser(_m))
	return &MonthlyUniqueUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MonthlyUniqueUserClient) UpdateOneID(id int) *MonthlyUniqueUserUpdateOne {
	mutation := newMonthlyUniqueUserMutation(c.config, OpUpdateOne, withMonthlyUniqueUserID(id))
	return &MonthlyUniqueUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MonthlyUniqueUser.
func (c *MonthlyUniqueUserClient) Delete() *MonthlyUniqueUserDelete {
	mutation := newMonthlyUniqueUserMutation(c.config, OpDelete)
	return &MonthlyUniqueUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MonthlyUniqueUserClient) DeleteOne(_m *MonthlyUniqueUser) *MonthlyUniqueUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MonthlyUniqueUserClient) DeleteOneID(id int) *MonthlyUniqueUserDeleteOne {
	builder := c.Delete().Where(monthlyuniqueuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MonthlyUniqueUserDeleteOne{builder}
}

// Query returns a query builder for MonthlyUniqueUser.
func (c *MonthlyUniqueUserClient) Query() *MonthlyUniqueUserQuery {
	return &MonthlyUniqueUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMonthlyUniqueUser},
		inters: c.Interceptors(),
	}
}

// Get returns a MonthlyUniqueUser entity by its id.
func (c *MonthlyUniqueUserClient) Get(ctx context.Context, id int) (*MonthlyUniqueUser, error) {
	return c.Query().Where(monthlyuniqueuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MonthlyUniqueUserClient) GetX(ctx context.Context, id int) *MonthlyUniqueUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MonthlyUniqueUserClient) Hooks() []Hook {
	return c.hooks.MonthlyUniqueUser
}

// Interceptors returns the client interceptors.
func (c *MonthlyUniqueUserClient) Interceptors() []Interceptor {
	return c.inters.MonthlyUniqueUser
}

func (c *MonthlyUniqueUserClient) mutate(ctx context.Context, m *MonthlyUniqueUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MonthlyUniqueUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MonthlyUniqueUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MonthlyUniqueUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MonthlyUniqueUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MonthlyUniqueUser mutation op: %q", m.Op())
	}
}

// UserLoginClient is a client for the UserLogin schema.
type UserLoginClient struct {
	config
}

// NewUserLoginClient returns a client for the UserLogin from the given config.
func NewUserLoginClient(c config) *UserLoginClient {
	return &UserLoginClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userlogin.Hooks(f(g(h())))`.
func (c *UserLoginClient) Use(hooks ...Hook) {
	c.hooks.UserLogin = append(c.hooks.UserLogin, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userlogin.Intercept(f(g(h())))`.
func (c *UserLoginClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserLogin = append(c.inters.UserLogin, interceptors...)
}

// Create returns a builder for creating a UserLogin entity.
func (c *UserLoginClient) Create() *UserLoginCreate {
	mutation := newUserLoginMutation(c.config, OpCreate)
	return &UserLoginCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserLogin entities.
func (c *UserLoginClient) CreateBulk(builders ...*UserLoginCreate) *UserLoginCreateBulk {
	return &UserLoginCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserLoginClient) MapCreateBulk(slice any, setFunc func(*UserLoginCreate, int)) *UserLoginCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserLoginCreateBulk{err: fmt.Errorf("calling to UserLoginClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserLoginCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserLoginCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserLogin.
func (c *UserLoginClient) Update() *UserLoginUpdate {
	mutation := newUserLoginMutation(c.config, OpUpdate)
	return &UserLoginUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserLoginClient) UpdateOne(_m *UserLogin) *UserLoginUpdateOne {
	mutation := newUserLoginMutation(c.config, OpUpdateOne, withUserLogin(_m))
	return &UserLoginUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserLoginClient) UpdateOneID(id int) *UserLoginUpdateOne {
	mutation := newUserLoginMutation(c.config, OpUpdateOne, withUserLoginID(id))
	return &UserLoginUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserLogin.
func (c *UserLoginClient) Delete() *UserLoginDelete {
	mutation := newUserLoginMutation(c.config, OpDelete)
	return &UserLoginDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserLoginClient) DeleteOne(_m *UserLogin) *UserLoginDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserLoginClient) DeleteOneID(id int) *UserLoginDeleteOne {
	builder := c.Delete().Where(userlogin.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserLoginDeleteOne{builder}
}

// Query returns a query builder for UserLogin.
func (c *UserLoginClient) Query() *UserLoginQuery {
	return &UserLoginQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserLogin},
		inters: c.Interceptors(),
	}
}

// Get returns a UserLogin entity by its id.
func (c *UserLoginClient) Get(ctx context.Context, id int) (*UserLogin, error) {
	return c.Query().Where(userlogin.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserLoginClient) GetX(ctx context.Context, id int) *UserLogin {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserLoginClient) Hooks() []Hook {
	return c.hooks.UserLogin
}

// Interceptors returns the client interceptors.
func (c *UserLoginClient) Interceptors() []Interceptor {
	return c.inters.UserLogin
}

func (c *UserLoginClient) mutate(ctx context.Context, m *UserLoginMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserLoginCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserLoginUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserLoginUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserLoginDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserLogin mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		DailyUniqueUser, MonthlyUniqueUser, UserLogin []ent.Hook
	}
	inters struct {
		DailyUniqueUser, MonthlyUniqueUser, UserLogin []ent.Interceptor
	}
)
