// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/choonhong/user-analytics/ent/dailyuniqueuser"
	"github.com/google/uuid"
)

// DailyUniqueUser is the model entity for the DailyUniqueUser schema.
type DailyUniqueUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Date holds the value of the "date" field.
	Date string `json:"date,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID       uuid.UUID `json:"user_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyUniqueUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailyuniqueuser.FieldID:
			values[i] = new(sql.NullInt64)
		case dailyuniqueuser.FieldDate:
			values[i] = new(sql.NullString)
		case dailyuniqueuser.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyUniqueUser fields.
func (_m *DailyUniqueUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailyuniqueuser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dailyuniqueuser.FieldDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.String
			}
		case dailyuniqueuser.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyUniqueUser.
// This includes values selected through modifiers, order, etc.
func (_m *DailyUniqueUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DailyUniqueUser.
// Note that you need to call DailyUniqueUser.Unwrap() before calling this method if this DailyUniqueUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DailyUniqueUser) Update() *DailyUniqueUserUpdateOne {
	return NewDailyUniqueUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DailyUniqueUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DailyUniqueUser) Unwrap() *DailyUniqueUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyUniqueUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DailyUniqueUser) String() string {
	var builder strings.Builder
	builder.WriteString("DailyUniqueUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date=")
	builder.WriteString(_m.Date)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// DailyUniqueUsers is a parsable slice of DailyUniqueUser.
type DailyUniqueUsers []*DailyUniqueUser
