// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/user-analytics/ent/monthlyuniqueuser"
	"github.com/choonhong/user-analytics/ent/predicate"
	"github.com/google/uuid"
)

// MonthlyUniqueUserUpdate is the builder for updating MonthlyUniqueUser entities.
type MonthlyUniqueUserUpdate struct {
	config
	hooks    []Hook
	mutation *MonthlyUniqueUserMutation
}

// Where appends a list predicates to the MonthlyUniqueUserUpdate builder.
func (_u *MonthlyUniqueUserUpdate) Where(ps ...predicate.MonthlyUniqueUser) *MonthlyUniqueUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMonth sets the "month" field.
func (_u *MonthlyUniqueUserUpdate) SetMonth(v string) *MonthlyUniqueUserUpdate {
	_u.mutation.SetMonth(v)
	return _u
}

// SetNillableMonth sets the "month" field if the given value is not nil.
func (_u *MonthlyUniqueUserUpdate) SetNillableMonth(v *string) *MonthlyUniqueUserUpdate {
	if v != nil {
		_u.SetMonth(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MonthlyUniqueUserUpdate) SetUserID(v uuid.UUID) *MonthlyUniqueUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MonthlyUniqueUserUpdate) SetNillableUserID(v *uuid.UUID) *MonthlyUniqueUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// Mutation returns the MonthlyUniqueUserMutation object of the builder.
func (_u *MonthlyUniqueUserUpdate) Mutation() *MonthlyUniqueUserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MonthlyUniqueUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonthlyUniqueUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MonthlyUniqueUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonthlyUniqueUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MonthlyUniqueUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(monthlyuniqueuser.Table, monthlyuniqueuser.Columns, sqlgraph.NewFieldSpec(monthlyuniqueuser.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Month(); ok {
		_spec.SetField(monthlyuniqueuser.FieldMonth, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(monthlyuniqueuser.FieldUserID, field.TypeUUID, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monthlyuniqueuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MonthlyUniqueUserUpdateOne is the builder for updating a single MonthlyUniqueUser entity.
type MonthlyUniqueUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MonthlyUniqueUserMutation
}

// SetMonth sets the "month" field.
func (_u *MonthlyUniqueUserUpdateOne) SetMonth(v string) *MonthlyUniqueUserUpdateOne {
	_u.mutation.SetMonth(v)
	return _u
}

// SetNillableMonth sets the "month" field if the given value is not nil.
func (_u *MonthlyUniqueUserUpdateOne) SetNillableMonth(v *string) *MonthlyUniqueUserUpdateOne {
	if v != nil {
		_u.SetMonth(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MonthlyUniqueUserUpdateOne) SetUserID(v uuid.UUID) *MonthlyUniqueUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MonthlyUniqueUserUpdateOne) SetNillableUserID(v *uuid.UUID) *MonthlyUniqueUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// Mutation returns the MonthlyUniqueUserMutation object of the builder.
func (_u *MonthlyUniqueUserUpdateOne) Mutation() *MonthlyUniqueUserMutation {
	return _u.mutation
}

// Where appends a list predicates to the MonthlyUniqueUserUpdate builder.
func (_u *MonthlyUniqueUserUpdateOne) Where(ps ...predicate.MonthlyUniqueUser) *MonthlyUniqueUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MonthlyUniqueUserUpdateOne) Select(field string, fields ...string) *MonthlyUniqueUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MonthlyUniqueUser entity.
func (_u *MonthlyUniqueUserUpdateOne) Save(ctx context.Context) (*MonthlyUniqueUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonthlyUniqueUserUpdateOne) SaveX(ctx context.Context) *MonthlyUniqueUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MonthlyUniqueUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonthlyUniqueUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MonthlyUniqueUserUpdateOne) sqlSave(ctx context.Context) (_node *MonthlyUniqueUser, err error) {
	_spec := sqlgraph.NewUpdateSpec(monthlyuniqueuser.Table, monthlyuniqueuser.Columns, sqlgraph.NewFieldSpec(monthlyuniqueuser.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MonthlyUniqueUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monthlyuniqueuser.FieldID)
		for _, f := range fields {
			if !monthlyuniqueuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monthlyuniqueuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Month(); ok {
		_spec.SetField(monthlyuniqueuser.FieldMonth, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(monthlyuniqueuser.FieldUserID, field.TypeUUID, value)
	}
	_node = &MonthlyUniqueUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monthlyuniqueuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
