// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/choonhong/user-analytics/ent/dailyuniqueuser"
	"github.com/choonhong/user-analytics/ent/monthlyuniqueuser"
	"github.com/choonhong/user-analytics/ent/predicate"
	"github.com/choonhong/user-analytics/ent/userlogin"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDailyUniqueUser   = "DailyUniqueUser"
	TypeMonthlyUniqueUser = "MonthlyUniqueUser"
	TypeUserLogin         = "UserLogin"
)

// DailyUniqueUserMutation represents an operation that mutates the DailyUniqueUser nodes in the graph.
type DailyUniqueUserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	date          *string
	user_id       *uuid.UUID
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*DailyUniqueUser, error)
	predicates    []predicate.DailyUniqueUser
}

var _ ent.Mutation = (*DailyUniqueUserMutation)(nil)

// dailyuniqueuserOption allows management of the mutation configuration using functional options.
type dailyuniqueuserOption func(*DailyUniqueUserMutation)

// newDailyUniqueUserMutation creates new mutation for the DailyUniqueUser entity.
func newDailyUniqueUserMutation(c config, op Op, opts ...dailyuniqueuserOption) *DailyUniqueUserMutation {
	m := &DailyUniqueUserMutation{
		config:        c,
		op:            op,
		typ:           TypeDailyUniqueUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDailyUniqueUserID sets the ID field of the mutation.
func withDailyUniqueUserID(id int) dailyuniqueuserOption {
	return func(m *DailyUniqueUserMutation) {
		var (
			err   error
			once  sync.Once
			value *DailyUniqueUser
		)
		m.oldValue = func(ctx context.Context) (*DailyUniqueUser, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DailyUniqueUser.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDailyUniqueUser sets the old DailyUniqueUser of the mutation.
func withDailyUniqueUser(node *DailyUniqueUser) dailyuniqueuserOption {
	return func(m *DailyUniqueUserMutation) {
		m.oldValue = func(context.Context) (*DailyUniqueUser, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DailyUniqueUserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DailyUniqueUserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DailyUniqueUserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DailyUniqueUserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DailyUniqueUser.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDate sets the "date" field.
func (m *DailyUniqueUserMutation) SetDate(s string) {
	m.date = &s
}

// Date returns the value of the "date" field in the mutation.
func (m *DailyUniqueUserMutation) Date() (r string, exists bool) {
	v := m.date
	if v == nil {
		return
	}
	return *v, true
}

// OldDate returns the old "date" field's value of the DailyUniqueUser entity.
// If the DailyUniqueUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyUniqueUserMutation) OldDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDate: %w", err)
	}
	return oldValue.Date, nil
}

// ResetDate resets all changes to the "date" field.
func (m *DailyUniqueUserMutation) ResetDate() {
	m.date = nil
}

// SetUserID sets the "user_id" field.
func (m *DailyUniqueUserMutation) SetUserID(u uuid.UUID) {
	m.user_id = &u
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *DailyUniqueUserMutation) UserID() (r uuid.UUID, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the DailyUniqueUser entity.
// If the DailyUniqueUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyUniqueUserMutation) OldUserID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *DailyUniqueUserMutation) ResetUserID() {
	m.user_id = nil
}

// Where appends a list predicates to the DailyUniqueUserMutation builder.
func (m *DailyUniqueUserMutation) Where(ps ...predicate.DailyUniqueUser) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DailyUniqueUserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DailyUniqueUserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DailyUniqueUser, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DailyUniqueUserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DailyUniqueUserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DailyUniqueUser).
func (m *DailyUniqueUserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DailyUniqueUserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.date != nil {
		fields = append(fields, dailyuniqueuser.FieldDate)
	}
	if m.user_id != nil {
		fields = append(fields, dailyuniqueuser.FieldUserID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DailyUniqueUserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dailyuniqueuser.FieldDate:
		return m.Date()
	case dailyuniqueuser.FieldUserID:
		return m.UserID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DailyUniqueUserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dailyuniqueuser.FieldDate:
		return m.OldDate(ctx)
	case dailyuniqueuser.FieldUserID:
		return m.OldUserID(ctx)
	}
	return nil, fmt.Errorf("unknown DailyUniqueUser field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DailyUniqueUserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dailyuniqueuser.FieldDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDate(v)
		return nil
	case dailyuniqueuser.FieldUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	}
	return fmt.Errorf("unknown DailyUniqueUser field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DailyUniqueUserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DailyUniqueUserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DailyUniqueUserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown DailyUniqueUser numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DailyUniqueUserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DailyUniqueUserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DailyUniqueUserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown DailyUniqueUser nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DailyUniqueUserMutation) ResetField(name string) error {
	switch name {
	case dailyuniqueuser.FieldDate:
		m.ResetDate()
		return nil
	case dailyuniqueuser.FieldUserID:
		m.ResetUserID()
		return nil
	}
	return fmt.Errorf("unknown DailyUniqueUser field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DailyUniqueUserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DailyUniqueUserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DailyUniqueUserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DailyUniqueUserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DailyUniqueUserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DailyUniqueUserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DailyUniqueUserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown DailyUniqueUser unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DailyUniqueUserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown DailyUniqueUser edge %s", name)
}

// MonthlyUniqueUserMutation represents an operation that mutates the MonthlyUniqueUser nodes in the graph.
type MonthlyUniqueUserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	month         *string
	user_id       *uuid.UUID
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*MonthlyUniqueUser, error)
	predicates    []predicate.MonthlyUniqueUser
}

var _ ent.Mutation = (*MonthlyUniqueUserMutation)(nil)

// monthlyuniqueuserOption allows management of the mutation configuration using functional options.
type monthlyuniqueuserOption func(*MonthlyUniqueUserMutation)

// newMonthlyUniqueUserMutation creates new mutation for the MonthlyUniqueUser entity.
func newMonthlyUniqueUserMutation(c config, op Op, opts ...monthlyuniqueuserOption) *MonthlyUniqueUserMutation {
	m := &MonthlyUniqueUserMutation{
		config:        c,
		op:            op,
		typ:           TypeMonthlyUniqueUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMonthlyUniqueUserID sets the ID field of the mutation.
func withMonthlyUniqueUserID(id int) monthlyuniqueuserOption {
	return func(m *MonthlyUniqueUserMutation) {
		var (
			err   error
			once  sync.Once
			value *MonthlyUniqueUser
		)
		m.oldValue = func(ctx context.Context) (*MonthlyUniqueUser, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MonthlyUniqueUser.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMonthlyUniqueUser sets the old MonthlyUniqueUser of the mutation.
func withMonthlyUniqueUser(node *MonthlyUniqueUser) monthlyuniqueuserOption {
	return func(m *MonthlyUniqueUserMutation) {
		m.oldValue = func(context.Context) (*MonthlyUniqueUser, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MonthlyUniqueUserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MonthlyUniqueUserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MonthlyUniqueUserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MonthlyUniqueUserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MonthlyUniqueUser.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetMonth sets the "month" field.
func (m *MonthlyUniqueUserMutation) SetMonth(s string) {
	m.month = &s
}

// Month returns the value of the "month" field in the mutation.
func (m *MonthlyUniqueUserMutation) Month() (r string, exists bool) {
	v := m.month
	if v == nil {
		return
	}
	return *v, true
}

// OldMonth returns the old "month" field's value of the MonthlyUniqueUser entity.
// If the MonthlyUniqueUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonthlyUniqueUserMutation) OldMonth(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMonth is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMonth requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMonth: %w", err)
	}
	return oldValue.Month, nil
}

// ResetMonth resets all changes to the "month" field.
func (m *MonthlyUniqueUserMutation) ResetMonth() {
	m.month = nil
}

// SetUserID sets the "user_id" field.
func (m *MonthlyUniqueUserMutation) SetUserID(u uuid.UUID) {
	m.user_id = &u
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *MonthlyUniqueUserMutation) UserID() (r uuid.UUID, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the MonthlyUniqueUser entity.
// If the MonthlyUniqueUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MonthlyUniqueUserMutation) OldUserID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *MonthlyUniqueUserMutation) ResetUserID() {
	m.user_id = nil
}

// Where appends a list predicates to the MonthlyUniqueUserMutation builder.
func (m *MonthlyUniqueUserMutation) Where(ps ...predicate.MonthlyUniqueUser) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MonthlyUniqueUserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MonthlyUniqueUserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MonthlyUniqueUser, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MonthlyUniqueUserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MonthlyUniqueUserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MonthlyUniqueUser).
func (m *MonthlyUniqueUserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MonthlyUniqueUserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.month != nil {
		fields = append(fields, monthlyuniqueuser.FieldMonth)
	}
	if m.user_id != nil {
		fields = append(fields, monthlyuniqueuser.FieldUserID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MonthlyUniqueUserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case monthlyuniqueuser.FieldMonth:
		return m.Month()
	case monthlyuniqueuser.FieldUserID:
		return m.UserID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MonthlyUniqueUserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case monthlyuniqueuser.FieldMonth:
		return m.OldMonth(ctx)
	case monthlyuniqueuser.FieldUserID:
		return m.OldUserID(ctx)
	}
	return nil, fmt.Errorf("unknown MonthlyUniqueUser field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MonthlyUniqueUserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case monthlyuniqueuser.FieldMonth:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMonth(v)
		return nil
	case monthlyuniqueuser.FieldUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	}
	return fmt.Errorf("unknown MonthlyUniqueUser field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MonthlyUniqueUserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MonthlyUniqueUserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MonthlyUniqueUserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown MonthlyUniqueUser numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MonthlyUniqueUserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MonthlyUniqueUserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MonthlyUniqueUserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown MonthlyUniqueUser nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MonthlyUniqueUserMutation) ResetField(name string) error {
	switch name {
	case monthlyuniqueuser.FieldMonth:
		m.ResetMonth()
		return nil
	case monthlyuniqueuser.FieldUserID:
		m.ResetUserID()
		return nil
	}
	return fmt.Errorf("unknown MonthlyUniqueUser field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MonthlyUniqueUserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MonthlyUniqueUserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MonthlyUniqueUserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MonthlyUniqueUserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MonthlyUniqueUserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MonthlyUniqueUserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MonthlyUniqueUserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MonthlyUniqueUser unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MonthlyUniqueUserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MonthlyUniqueUser edge %s", name)
}

// UserLoginMutation represents an operation that mutates the UserLogin nodes in the graph.
type UserLoginMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user_id       *uuid.UUID
	login_time    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*UserLogin, error)
	predicates    []predicate.UserLogin
}

var _ ent.Mutation = (*UserLoginMutation)(nil)

// userloginOption allows management of the mutation configuration using functional options.
type userloginOption func(*UserLoginMutation)

// newUserLoginMutation creates new mutation for the UserLogin entity.
func newUserLoginMutation(c config, op Op, opts ...userloginOption) *UserLoginMutation {
	m := &UserLoginMutation{
		config:        c,
		op:            op,
		typ:           TypeUserLogin,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserLoginID sets the ID field of the mutation.
func withUserLoginID(id int) userloginOption {
	return func(m *UserLoginMutation) {
		var (
			err   error
			once  sync.Once
			value *UserLogin
		)
		m.oldValue = func(ctx context.Context) (*UserLogin, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserLogin.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserLogin sets the old UserLogin of the mutation.
func withUserLogin(node *UserLogin) userloginOption {
	return func(m *UserLoginMutation) {
		m.oldValue = func(context.Context) (*UserLogin, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserLoginMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserLoginMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserLoginMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserLoginMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UserLogin.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *UserLoginMutation) SetUserID(u uuid.UUID) {
	m.user_id = &u
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserLoginMutation) UserID() (r uuid.UUID, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the UserLogin entity.
// If the UserLogin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserLoginMutation) OldUserID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserLoginMutation) ResetUserID() {
	m.user_id = nil
}

// SetLoginTime sets the "login_time" field.
func (m *UserLoginMutation) SetLoginTime(t time.Time) {
	m.login_time = &t
}

// LoginTime returns the value of the "login_time" field in the mutation.
func (m *UserLoginMutation) LoginTime() (r time.Time, exists bool) {
	v := m.login_time
	if v == nil {
		return
	}
	return *v, true
}

// OldLoginTime returns the old "login_time" field's value of the UserLogin entity.
// If the UserLogin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserLoginMutation) OldLoginTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLoginTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLoginTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLoginTime: %w", err)
	}
	return oldValue.LoginTime, nil
}

// ResetLoginTime resets all changes to the "login_time" field.
func (m *UserLoginMutation) ResetLoginTime() {
	m.login_time = nil
}

// Where appends a list predicates to the UserLoginMutation builder.
func (m *UserLoginMutation) Where(ps ...predicate.UserLogin) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserLoginMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserLoginMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UserLogin, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserLoginMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserLoginMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UserLogin).
func (m *UserLoginMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserLoginMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.user_id != nil {
		fields = append(fields, userlogin.FieldUserID)
	}
	if m.login_time != nil {
		fields = append(fields, userlogin.FieldLoginTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserLoginMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case userlogin.FieldUserID:
		return m.UserID()
	case userlogin.FieldLoginTime:
		return m.LoginTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserLoginMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case userlogin.FieldUserID:
		return m.OldUserID(ctx)
	case userlogin.FieldLoginTime:
		return m.OldLoginTime(ctx)
	}
	return nil, fmt.Errorf("unknown UserLogin field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserLoginMutation) SetField(name string, value ent.Value) error {
	switch name {
	case userlogin.FieldUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case userlogin.FieldLoginTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLoginTime(v)
		return nil
	}
	return fmt.Errorf("unknown UserLogin field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserLoginMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserLoginMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserLoginMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UserLogin numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserLoginMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserLoginMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserLoginMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserLogin nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserLoginMutation) ResetField(name string) error {
	switch name {
	case userlogin.FieldUserID:
		m.ResetUserID()
		return nil
	case userlogin.FieldLoginTime:
		m.ResetLoginTime()
		return nil
	}
	return fmt.Errorf("unknown UserLogin field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserLoginMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserLoginMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserLoginMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserLoginMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserLoginMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserLoginMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserLoginMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown UserLogin unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserLoginMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown UserLogin edge %s", name)
}
