// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/choonhong/user-analytics/ent/userlogin"
	"github.com/google/uuid"
)

// UserLogin is the model entity for the UserLogin schema.
type UserLogin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// LoginTime holds the value of the "login_time" field.
	LoginTime    time.Time `json:"login_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserLogin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userlogin.FieldID:
			values[i] = new(sql.NullInt64)
		case userlogin.FieldLoginTime:
			values[i] = new(sql.NullTime)
		case userlogin.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserLogin fields.
func (_m *UserLogin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userlogin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userlogin.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case userlogin.FieldLoginTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field login_time", values[i])
			} else if value.Valid {
				_m.LoginTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserLogin.
// This includes values selected through modifiers, order, etc.
func (_m *UserLogin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserLogin.
// Note that you need to call UserLogin.Unwrap() before calling this method if this UserLogin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserLogin) Update() *UserLoginUpdateOne {
	return NewUserLoginClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserLogin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserLogin) Unwrap() *UserLogin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserLogin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserLogin) String() string {
	var builder strings.Builder
	builder.WriteString("UserLogin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("login_time=")
	builder.WriteString(_m.LoginTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserLogins is a parsable slice of UserLogin.
type UserLogins []*UserLogin
