// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsService creates a new instance of MockAnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsService {
	mock := &MockAnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsService is an autogenerated mock type for the AnalyticsService type
type MockAnalyticsService struct {
	mock.Mock
}

type MockAnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsService) EXPECT() *MockAnalyticsService_Expecter {
	return &MockAnalyticsService_Expecter{mock: &_m.Mock}
}

// GetDailyUserCount provides a mock function for the type MockAnalyticsService
func (_mock *MockAnalyticsService) GetDailyUserCount(ctx context.Context, date string) (int, error) {
	ret := _mock.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyUserCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, date)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsService_GetDailyUserCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyUserCount'
type MockAnalyticsService_GetDailyUserCount_Call struct {
	*mock.Call
}

// GetDailyUserCount is a helper method to define mock.On call
//   - ctx context.Context
//   - date string
func (_e *MockAnalyticsService_Expecter) GetDailyUserCount(ctx interface{}, date interface{}) *MockAnalyticsService_GetDailyUserCount_Call {
	return &MockAnalyticsService_GetDailyUserCount_Call{Call: _e.mock.On("GetDailyUserCount", ctx, date)}
}

func (_c *MockAnalyticsService_GetDailyUserCount_Call) Run(run func(ctx context.Context, date string)) *MockAnalyticsService_GetDailyUserCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsService_GetDailyUserCount_Call) Return(n int, err error) *MockAnalyticsService_GetDailyUserCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAnalyticsService_GetDailyUserCount_Call) RunAndReturn(run func(ctx context.Context, date string) (int, error)) *MockAnalyticsService_GetDailyUserCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyUserCount provides a mock function for the type MockAnalyticsService
func (_mock *MockAnalyticsService) GetMonthlyUserCount(ctx context.Context, month string) (int, error) {
	ret := _mock.Called(ctx, month)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyUserCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, month)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, month)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, month)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsService_GetMonthlyUserCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyUserCount'
type MockAnalyticsService_GetMonthlyUserCount_Call struct {
	*mock.Call
}

// GetMonthlyUserCount is a helper method to define mock.On call
//   - ctx context.Context
//   - month string
func (_e *MockAnalyticsService_Expecter) GetMonthlyUserCount(ctx interface{}, month interface{}) *MockAnalyticsService_GetMonthlyUserCount_Call {
	return &MockAnalyticsService_GetMonthlyUserCount_Call{Call: _e.mock.On("GetMonthlyUserCount", ctx, month)}
}

func (_c *MockAnalyticsService_GetMonthlyUserCount_Call) Run(run func(ctx context.Context, month string)) *MockAnalyticsService_GetMonthlyUserCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsService_GetMonthlyUserCount_Call) Return(n int, err error) *MockAnalyticsService_GetMonthlyUserCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAnalyticsService_GetMonthlyUserCount_Call) RunAndReturn(run func(ctx context.Context, month string) (int, error)) *MockAnalyticsService_GetMonthlyUserCount_Call {
	_c.Call.Return(run)
	return _c
}

// RecordLogin provides a mock function for the type MockAnalyticsService
func (_mock *MockAnalyticsService) RecordLogin(ctx context.Context, userID uuid.UUID, loginTime time.Time) error {
	ret := _mock.Called(ctx, userID, loginTime)

	if len(ret) == 0 {
		panic("no return value specified for RecordLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, loginTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalyticsService_RecordLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordLogin'
type MockAnalyticsService_RecordLogin_Call struct {
	*mock.Call
}

// RecordLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - loginTime time.Time
func (_e *MockAnalyticsService_Expecter) RecordLogin(ctx interface{}, userID interface{}, loginTime interface{}) *MockAnalyticsService_RecordLogin_Call {
	return &MockAnalyticsService_RecordLogin_Call{Call: _e.mock.On("RecordLogin", ctx, userID, loginTime)}
}

func (_c *MockAnalyticsService_RecordLogin_Call) Run(run func(ctx context.Context, userID uuid.UUID, loginTime time.Time)) *MockAnalyticsService_RecordLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsService_RecordLogin_Call) Return(err error) *MockAnalyticsService_RecordLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalyticsService_RecordLogin_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, loginTime time.Time) error) *MockAnalyticsService_RecordLogin_Call {
	_c.Call.Return(run)
	return _c
}
