// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DailyUniqueUsersColumns holds the columns for the "daily_unique_users" table.
	DailyUniqueUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// DailyUniqueUsersTable holds the schema information for the "daily_unique_users" table.
	DailyUniqueUsersTable = &schema.Table{
		Name:       "daily_unique_users",
		Columns:    DailyUniqueUsersColumns,
		PrimaryKey: []*schema.Column{DailyUniqueUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dailyuniqueuser_date_user_id",
				Unique:  true,
				Columns: []*schema.Column{DailyUniqueUsersColumns[1], DailyUniqueUsersColumns[2]},
			},
		},
	}
	// MonthlyUniqueUsersColumns holds the columns for the "monthly_unique_users" table.
	MonthlyUniqueUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "month", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// MonthlyUniqueUsersTable holds the schema information for the "monthly_unique_users" table.
	MonthlyUniqueUsersTable = &schema.Table{
		Name:       "monthly_unique_users",
		Columns:    MonthlyUniqueUsersColumns,
		PrimaryKey: []*schema.Column{MonthlyUniqueUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "monthlyuniqueuser_month_user_id",
				Unique:  true,
				Columns: []*schema.Column{MonthlyUniqueUsersColumns[1], MonthlyUniqueUsersColumns[2]},
			},
		},
	}
	// UserLoginsColumns holds the columns for the "user_logins" table.
	UserLoginsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "login_time", Type: field.TypeTime},
	}
	// UserLoginsTable holds the schema information for the "user_logins" table.
	UserLoginsTable = &schema.Table{
		Name:       "user_logins",
		Columns:    UserLoginsColumns,
		PrimaryKey: []*schema.Column{UserLoginsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userlogin_user_id_login_time",
				Unique:  true,
				Columns: []*schema.Column{UserLoginsColumns[1], UserLoginsColumns[2]},
			},
			{
				Name:    "userlogin_login_time",
				Unique:  false,
				Columns: []*schema.Column{UserLoginsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DailyUniqueUsersTable,
		MonthlyUniqueUsersTable,
		UserLoginsTable,
	}
)

func init() {
}
