// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/user-analytics/db/ent/dailyuniqueuser"
	"github.com/google/uuid"
)

// DailyUniqueUserCreate is the builder for creating a DailyUniqueUser entity.
type DailyUniqueUserCreate struct {
	config
	mutation *DailyUniqueUserMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (_c *DailyUniqueUserCreate) SetDate(v string) *DailyUniqueUserCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DailyUniqueUserCreate) SetUserID(v uuid.UUID) *DailyUniqueUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// Mutation returns the DailyUniqueUserMutation object of the builder.
func (_c *DailyUniqueUserCreate) Mutation() *DailyUniqueUserMutation {
	return _c.mutation
}

// Save creates the DailyUniqueUser in the database.
func (_c *DailyUniqueUserCreate) Save(ctx context.Context) (*DailyUniqueUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyUniqueUserCreate) SaveX(ctx context.Context) *DailyUniqueUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyUniqueUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyUniqueUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyUniqueUserCreate) check() error {
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "DailyUniqueUser.date"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DailyUniqueUser.user_id"`)}
	}
	return nil
}

func (_c *DailyUniqueUserCreate) sqlSave(ctx context.Context) (*DailyUniqueUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyUniqueUserCreate) createSpec() (*DailyUniqueUser, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyUniqueUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailyuniqueuser.Table, sqlgraph.NewFieldSpec(dailyuniqueuser.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(dailyuniqueuser.FieldDate, field.TypeString, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(dailyuniqueuser.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	return _node, _spec
}

// DailyUniqueUserCreateBulk is the builder for creating many DailyUniqueUser entities in bulk.
type DailyUniqueUserCreateBulk struct {
	config
	err      error
	builders []*DailyUniqueUserCreate
}

// Save creates the DailyUniqueUser entities in the database.
func (_c *DailyUniqueUserCreateBulk) Save(ctx context.Context) ([]*DailyUniqueUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyUniqueUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyUniqueUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyUniqueUserCreateBulk) SaveX(ctx context.Context) []*DailyUniqueUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyUniqueUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyUniqueUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
