// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/user-analytics/db/ent/dailyuniqueuser"
	"github.com/google/uuid"
)

// DailyUniqueUserCreate is the builder for creating a DailyUniqueUser entity.
type DailyUniqueUserCreate struct {
	config
	mutation *DailyUniqueUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDate sets the "date" field.
func (_c *DailyUniqueUserCreate) SetDate(v string) *DailyUniqueUserCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DailyUniqueUserCreate) SetUserID(v uuid.UUID) *DailyUniqueUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// Mutation returns the DailyUniqueUserMutation object of the builder.
func (_c *DailyUniqueUserCreate) Mutation() *DailyUniqueUserMutation {
	return _c.mutation
}

// Save creates the DailyUniqueUser in the database.
func (_c *DailyUniqueUserCreate) Save(ctx context.Context) (*DailyUniqueUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyUniqueUserCreate) SaveX(ctx context.Context) *DailyUniqueUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyUniqueUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyUniqueUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyUniqueUserCreate) check() error {
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "DailyUniqueUser.date"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DailyUniqueUser.user_id"`)}
	}
	return nil
}

func (_c *DailyUniqueUserCreate) sqlSave(ctx context.Context) (*DailyUniqueUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyUniqueUserCreate) createSpec() (*DailyUniqueUser, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyUniqueUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailyuniqueuser.Table, sqlgraph.NewFieldSpec(dailyuniqueuser.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(dailyuniqueuser.FieldDate, field.TypeString, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(dailyuniqueuser.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyUniqueUser.Create().
//		SetDate(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyUniqueUserUpsert) {
//			SetDate(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyUniqueUserCreate) OnConflict(opts ...sql.ConflictOption) *DailyUniqueUserUpsertOne {
	_c.conflict = opts
	return &DailyUniqueUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyUniqueUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyUniqueUserCreate) OnConflictColumns(columns ...string) *DailyUniqueUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyUniqueUserUpsertOne{
		create: _c,
	}
}

type (
	// DailyUniqueUserUpsertOne is the builder for "upsert"-ing
	//  one DailyUniqueUser node.
	DailyUniqueUserUpsertOne struct {
		create *DailyUniqueUserCreate
	}

	// DailyUniqueUserUpsert is the "OnConflict" setter.
	DailyUniqueUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetDate sets the "date" field.
func (u *DailyUniqueUserUpsert) SetDate(v string) *DailyUniqueUserUpsert {
	u.Set(dailyuniqueuser.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *DailyUniqueUserUpsert) UpdateDate() *DailyUniqueUserUpsert {
	u.SetExcluded(dailyuniqueuser.FieldDate)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DailyUniqueUserUpsert) SetUserID(v uuid.UUID) *DailyUniqueUserUpsert {
	u.Set(dailyuniqueuser.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyUniqueUserUpsert) UpdateUserID() *DailyUniqueUserUpsert {
	u.SetExcluded(dailyuniqueuser.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DailyUniqueUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyUniqueUserUpsertOne) UpdateNewValues() *DailyUniqueUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyUniqueUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DailyUniqueUserUpsertOne) Ignore() *DailyUniqueUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyUniqueUserUpsertOne) DoNothing() *DailyUniqueUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyUniqueUserCreate.OnConflict
// documentation for more info.
func (u *DailyUniqueUserUpsertOne) Update(set func(*DailyUniqueUserUpsert)) *DailyUniqueUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyUniqueUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetDate sets the "date" field.
func (u *DailyUniqueUserUpsertOne) SetDate(v string) *DailyUniqueUserUpsertOne {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *DailyUniqueUserUpsertOne) UpdateDate() *DailyUniqueUserUpsertOne {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.UpdateDate()
	})
}

// SetUserID sets the "user_id" field.
func (u *DailyUniqueUserUpsertOne) SetUserID(v uuid.UUID) *DailyUniqueUserUpsertOne {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyUniqueUserUpsertOne) UpdateUserID() *DailyUniqueUserUpsertOne {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *DailyUniqueUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyUniqueUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyUniqueUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DailyUniqueUserUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DailyUniqueUserUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DailyUniqueUserCreateBulk is the builder for creating many DailyUniqueUser entities in bulk.
type DailyUniqueUserCreateBulk struct {
	config
	err      error
	builders []*DailyUniqueUserCreate
	conflict []sql.ConflictOption
}

// Save creates the DailyUniqueUser entities in the database.
func (_c *DailyUniqueUserCreateBulk) Save(ctx context.Context) ([]*DailyUniqueUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyUniqueUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyUniqueUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyUniqueUserCreateBulk) SaveX(ctx context.Context) []*DailyUniqueUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyUniqueUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyUniqueUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyUniqueUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyUniqueUserUpsert) {
//			SetDate(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyUniqueUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *DailyUniqueUserUpsertBulk {
	_c.conflict = opts
	return &DailyUniqueUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyUniqueUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyUniqueUserCreateBulk) OnConflictColumns(columns ...string) *DailyUniqueUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyUniqueUserUpsertBulk{
		create: _c,
	}
}

// DailyUniqueUserUpsertBulk is the builder for "upsert"-ing
// a bulk of DailyUniqueUser nodes.
type DailyUniqueUserUpsertBulk struct {
	create *DailyUniqueUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DailyUniqueUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyUniqueUserUpsertBulk) UpdateNewValues() *DailyUniqueUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyUniqueUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DailyUniqueUserUpsertBulk) Ignore() *DailyUniqueUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyUniqueUserUpsertBulk) DoNothing() *DailyUniqueUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyUniqueUserCreateBulk.OnConflict
// documentation for more info.
func (u *DailyUniqueUserUpsertBulk) Update(set func(*DailyUniqueUserUpsert)) *DailyUniqueUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyUniqueUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetDate sets the "date" field.
func (u *DailyUniqueUserUpsertBulk) SetDate(v string) *DailyUniqueUserUpsertBulk {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *DailyUniqueUserUpsertBulk) UpdateDate() *DailyUniqueUserUpsertBulk {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.UpdateDate()
	})
}

// SetUserID sets the "user_id" field.
func (u *DailyUniqueUserUpsertBulk) SetUserID(v uuid.UUID) *DailyUniqueUserUpsertBulk {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyUniqueUserUpsertBulk) UpdateUserID() *DailyUniqueUserUpsertBulk {
	return u.Update(func(s *DailyUniqueUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *DailyUniqueUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DailyUniqueUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyUniqueUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyUniqueUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
