// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/user-analytics/db/ent/dailyuniqueuser"
	"github.com/choonhong/user-analytics/db/ent/predicate"
	"github.com/google/uuid"
)

// DailyUniqueUserUpdate is the builder for updating DailyUniqueUser entities.
type DailyUniqueUserUpdate struct {
	config
	hooks    []Hook
	mutation *DailyUniqueUserMutation
}

// Where appends a list predicates to the DailyUniqueUserUpdate builder.
func (_u *DailyUniqueUserUpdate) Where(ps ...predicate.DailyUniqueUser) *DailyUniqueUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDate sets the "date" field.
func (_u *DailyUniqueUserUpdate) SetDate(v string) *DailyUniqueUserUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyUniqueUserUpdate) SetNillableDate(v *string) *DailyUniqueUserUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyUniqueUserUpdate) SetUserID(v uuid.UUID) *DailyUniqueUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyUniqueUserUpdate) SetNillableUserID(v *uuid.UUID) *DailyUniqueUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// Mutation returns the DailyUniqueUserMutation object of the builder.
func (_u *DailyUniqueUserUpdate) Mutation() *DailyUniqueUserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyUniqueUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyUniqueUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyUniqueUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyUniqueUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DailyUniqueUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dailyuniqueuser.Table, dailyuniqueuser.Columns, sqlgraph.NewFieldSpec(dailyuniqueuser.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailyuniqueuser.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailyuniqueuser.FieldUserID, field.TypeUUID, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailyuniqueuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyUniqueUserUpdateOne is the builder for updating a single DailyUniqueUser entity.
type DailyUniqueUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyUniqueUserMutation
}

// SetDate sets the "date" field.
func (_u *DailyUniqueUserUpdateOne) SetDate(v string) *DailyUniqueUserUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyUniqueUserUpdateOne) SetNillableDate(v *string) *DailyUniqueUserUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyUniqueUserUpdateOne) SetUserID(v uuid.UUID) *DailyUniqueUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyUniqueUserUpdateOne) SetNillableUserID(v *uuid.UUID) *DailyUniqueUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// Mutation returns the DailyUniqueUserMutation object of the builder.
func (_u *DailyUniqueUserUpdateOne) Mutation() *DailyUniqueUserMutation {
	return _u.mutation
}

// Where appends a list predicates to the DailyUniqueUserUpdate builder.
func (_u *DailyUniqueUserUpdateOne) Where(ps ...predicate.DailyUniqueUser) *DailyUniqueUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyUniqueUserUpdateOne) Select(field string, fields ...string) *DailyUniqueUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyUniqueUser entity.
func (_u *DailyUniqueUserUpdateOne) Save(ctx context.Context) (*DailyUniqueUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyUniqueUserUpdateOne) SaveX(ctx context.Context) *DailyUniqueUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyUniqueUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyUniqueUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DailyUniqueUserUpdateOne) sqlSave(ctx context.Context) (_node *DailyUniqueUser, err error) {
	_spec := sqlgraph.NewUpdateSpec(dailyuniqueuser.Table, dailyuniqueuser.Columns, sqlgraph.NewFieldSpec(dailyuniqueuser.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyUniqueUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailyuniqueuser.FieldID)
		for _, f := range fields {
			if !dailyuniqueuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailyuniqueuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailyuniqueuser.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailyuniqueuser.FieldUserID, field.TypeUUID, value)
	}
	_node = &DailyUniqueUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailyuniqueuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
