// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/user-analytics/db/ent/monthlyuniqueuser"
	"github.com/google/uuid"
)

// MonthlyUniqueUserCreate is the builder for creating a MonthlyUniqueUser entity.
type MonthlyUniqueUserCreate struct {
	config
	mutation *MonthlyUniqueUserMutation
	hooks    []Hook
}

// SetMonth sets the "month" field.
func (_c *MonthlyUniqueUserCreate) SetMonth(v string) *MonthlyUniqueUserCreate {
	_c.mutation.SetMonth(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MonthlyUniqueUserCreate) SetUserID(v uuid.UUID) *MonthlyUniqueUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// Mutation returns the MonthlyUniqueUserMutation object of the builder.
func (_c *MonthlyUniqueUserCreate) Mutation() *MonthlyUniqueUserMutation {
	return _c.mutation
}

// Save creates the MonthlyUniqueUser in the database.
func (_c *MonthlyUniqueUserCreate) Save(ctx context.Context) (*MonthlyUniqueUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MonthlyUniqueUserCreate) SaveX(ctx context.Context) *MonthlyUniqueUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonthlyUniqueUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonthlyUniqueUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MonthlyUniqueUserCreate) check() error {
	if _, ok := _c.mutation.Month(); !ok {
		return &ValidationError{Name: "month", err: errors.New(`ent: missing required field "MonthlyUniqueUser.month"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MonthlyUniqueUser.user_id"`)}
	}
	return nil
}

func (_c *MonthlyUniqueUserCreate) sqlSave(ctx context.Context) (*MonthlyUniqueUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MonthlyUniqueUserCreate) createSpec() (*MonthlyUniqueUser, *sqlgraph.CreateSpec) {
	var (
		_node = &MonthlyUniqueUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(monthlyuniqueuser.Table, sqlgraph.NewFieldSpec(monthlyuniqueuser.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Month(); ok {
		_spec.SetField(monthlyuniqueuser.FieldMonth, field.TypeString, value)
		_node.Month = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(monthlyuniqueuser.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	return _node, _spec
}

// MonthlyUniqueUserCreateBulk is the builder for creating many MonthlyUniqueUser entities in bulk.
type MonthlyUniqueUserCreateBulk struct {
	config
	err      error
	builders []*MonthlyUniqueUserCreate
}

// Save creates the MonthlyUniqueUser entities in the database.
func (_c *MonthlyUniqueUserCreateBulk) Save(ctx context.Context) ([]*MonthlyUniqueUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MonthlyUniqueUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonthlyUniqueUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MonthlyUniqueUserCreateBulk) SaveX(ctx context.Context) []*MonthlyUniqueUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonthlyUniqueUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonthlyUniqueUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
