// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/user-analytics/db/ent/predicate"
	"github.com/choonhong/user-analytics/db/ent/userlogin"
	"github.com/google/uuid"
)

// UserLoginUpdate is the builder for updating UserLogin entities.
type UserLoginUpdate struct {
	config
	hooks    []Hook
	mutation *UserLoginMutation
}

// Where appends a list predicates to the UserLoginUpdate builder.
func (_u *UserLoginUpdate) Where(ps ...predicate.UserLogin) *UserLoginUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserLoginUpdate) SetUserID(v uuid.UUID) *UserLoginUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLoginUpdate) SetNillableUserID(v *uuid.UUID) *UserLoginUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLoginTime sets the "login_time" field.
func (_u *UserLoginUpdate) SetLoginTime(v time.Time) *UserLoginUpdate {
	_u.mutation.SetLoginTime(v)
	return _u
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_u *UserLoginUpdate) SetNillableLoginTime(v *time.Time) *UserLoginUpdate {
	if v != nil {
		_u.SetLoginTime(*v)
	}
	return _u
}

// Mutation returns the UserLoginMutation object of the builder.
func (_u *UserLoginUpdate) Mutation() *UserLoginMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserLoginUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLoginUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserLoginUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLoginUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserLoginUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userlogin.Table, userlogin.Columns, sqlgraph.NewFieldSpec(userlogin.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userlogin.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LoginTime(); ok {
		_spec.SetField(userlogin.FieldLoginTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlogin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserLoginUpdateOne is the builder for updating a single UserLogin entity.
type UserLoginUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserLoginMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserLoginUpdateOne) SetUserID(v uuid.UUID) *UserLoginUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLoginUpdateOne) SetNillableUserID(v *uuid.UUID) *UserLoginUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLoginTime sets the "login_time" field.
func (_u *UserLoginUpdateOne) SetLoginTime(v time.Time) *UserLoginUpdateOne {
	_u.mutation.SetLoginTime(v)
	return _u
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_u *UserLoginUpdateOne) SetNillableLoginTime(v *time.Time) *UserLoginUpdateOne {
	if v != nil {
		_u.SetLoginTime(*v)
	}
	return _u
}

// Mutation returns the UserLoginMutation object of the builder.
func (_u *UserLoginUpdateOne) Mutation() *UserLoginMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserLoginUpdate builder.
func (_u *UserLoginUpdateOne) Where(ps ...predicate.UserLogin) *UserLoginUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserLoginUpdateOne) Select(field string, fields ...string) *UserLoginUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserLogin entity.
func (_u *UserLoginUpdateOne) Save(ctx context.Context) (*UserLogin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLoginUpdateOne) SaveX(ctx context.Context) *UserLogin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserLoginUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLoginUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserLoginUpdateOne) sqlSave(ctx context.Context) (_node *UserLogin, err error) {
	_spec := sqlgraph.NewUpdateSpec(userlogin.Table, userlogin.Columns, sqlgraph.NewFieldSpec(userlogin.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserLogin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userlogin.FieldID)
		for _, f := range fields {
			if !userlogin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userlogin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userlogin.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LoginTime(); ok {
		_spec.SetField(userlogin.FieldLoginTime, field.TypeTime, value)
	}
	_node = &UserLogin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlogin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
