// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/choonhong/user-analytics/db/ent/userlogin"
	"github.com/google/uuid"
)

// UserLoginCreate is the builder for creating a UserLogin entity.
type UserLoginCreate struct {
	config
	mutation *UserLoginMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserLoginCreate) SetUserID(v uuid.UUID) *UserLoginCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLoginTime sets the "login_time" field.
func (_c *UserLoginCreate) SetLoginTime(v time.Time) *UserLoginCreate {
	_c.mutation.SetLoginTime(v)
	return _c
}

// Mutation returns the UserLoginMutation object of the builder.
func (_c *UserLoginCreate) Mutation() *UserLoginMutation {
	return _c.mutation
}

// Save creates the UserLogin in the database.
func (_c *UserLoginCreate) Save(ctx context.Context) (*UserLogin, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserLoginCreate) SaveX(ctx context.Context) *UserLogin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLoginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLoginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserLoginCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserLogin.user_id"`)}
	}
	if _, ok := _c.mutation.LoginTime(); !ok {
		return &ValidationError{Name: "login_time", err: errors.New(`ent: missing required field "UserLogin.login_time"`)}
	}
	return nil
}

func (_c *UserLoginCreate) sqlSave(ctx context.Context) (*UserLogin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserLoginCreate) createSpec() (*UserLogin, *sqlgraph.CreateSpec) {
	var (
		_node = &UserLogin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userlogin.Table, sqlgraph.NewFieldSpec(userlogin.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userlogin.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.LoginTime(); ok {
		_spec.SetField(userlogin.FieldLoginTime, field.TypeTime, value)
		_node.LoginTime = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserLogin.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserLoginUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserLoginCreate) OnConflict(opts ...sql.ConflictOption) *UserLoginUpsertOne {
	_c.conflict = opts
	return &UserLoginUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserLogin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserLoginCreate) OnConflictColumns(columns ...string) *UserLoginUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserLoginUpsertOne{
		create: _c,
	}
}

type (
	// UserLoginUpsertOne is the builder for "upsert"-ing
	//  one UserLogin node.
	UserLoginUpsertOne struct {
		create *UserLoginCreate
	}

	// UserLoginUpsert is the "OnConflict" setter.
	UserLoginUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserLoginUpsert) SetUserID(v uuid.UUID) *UserLoginUpsert {
	u.Set(userlogin.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserLoginUpsert) UpdateUserID() *UserLoginUpsert {
	u.SetExcluded(userlogin.FieldUserID)
	return u
}

// SetLoginTime sets the "login_time" field.
func (u *UserLoginUpsert) SetLoginTime(v time.Time) *UserLoginUpsert {
	u.Set(userlogin.FieldLoginTime, v)
	return u
}

// UpdateLoginTime sets the "login_time" field to the value that was provided on create.
func (u *UserLoginUpsert) UpdateLoginTime() *UserLoginUpsert {
	u.SetExcluded(userlogin.FieldLoginTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserLogin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserLoginUpsertOne) UpdateNewValues() *UserLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserLogin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserLoginUpsertOne) Ignore() *UserLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserLoginUpsertOne) DoNothing() *UserLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserLoginCreate.OnConflict
// documentation for more info.
func (u *UserLoginUpsertOne) Update(set func(*UserLoginUpsert)) *UserLoginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserLoginUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserLoginUpsertOne) SetUserID(v uuid.UUID) *UserLoginUpsertOne {
	return u.Update(func(s *UserLoginUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserLoginUpsertOne) UpdateUserID() *UserLoginUpsertOne {
	return u.Update(func(s *UserLoginUpsert) {
		s.UpdateUserID()
	})
}

// SetLoginTime sets the "login_time" field.
func (u *UserLoginUpsertOne) SetLoginTime(v time.Time) *UserLoginUpsertOne {
	return u.Update(func(s *UserLoginUpsert) {
		s.SetLoginTime(v)
	})
}

// UpdateLoginTime sets the "login_time" field to the value that was provided on create.
func (u *UserLoginUpsertOne) UpdateLoginTime() *UserLoginUpsertOne {
	return u.Update(func(s *UserLoginUpsert) {
		s.UpdateLoginTime()
	})
}

// Exec executes the query.
func (u *UserLoginUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserLoginCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserLoginUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserLoginUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserLoginUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserLoginCreateBulk is the builder for creating many UserLogin entities in bulk.
type UserLoginCreateBulk struct {
	config
	err      error
	builders []*UserLoginCreate
	conflict []sql.ConflictOption
}

// Save creates the UserLogin entities in the database.
func (_c *UserLoginCreateBulk) Save(ctx context.Context) ([]*UserLogin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserLogin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserLoginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserLoginCreateBulk) SaveX(ctx context.Context) []*UserLogin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLoginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLoginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserLogin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserLoginUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserLoginCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserLoginUpsertBulk {
	_c.conflict = opts
	return &UserLoginUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserLogin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserLoginCreateBulk) OnConflictColumns(columns ...string) *UserLoginUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserLoginUpsertBulk{
		create: _c,
	}
}

// UserLoginUpsertBulk is the builder for "upsert"-ing
// a bulk of UserLogin nodes.
type UserLoginUpsertBulk struct {
	create *UserLoginCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserLogin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserLoginUpsertBulk) UpdateNewValues() *UserLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserLogin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserLoginUpsertBulk) Ignore() *UserLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserLoginUpsertBulk) DoNothing() *UserLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserLoginCreateBulk.OnConflict
// documentation for more info.
func (u *UserLoginUpsertBulk) Update(set func(*UserLoginUpsert)) *UserLoginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserLoginUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserLoginUpsertBulk) SetUserID(v uuid.UUID) *UserLoginUpsertBulk {
	return u.Update(func(s *UserLoginUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserLoginUpsertBulk) UpdateUserID() *UserLoginUpsertBulk {
	return u.Update(func(s *UserLoginUpsert) {
		s.UpdateUserID()
	})
}

// SetLoginTime sets the "login_time" field.
func (u *UserLoginUpsertBulk) SetLoginTime(v time.Time) *UserLoginUpsertBulk {
	return u.Update(func(s *UserLoginUpsert) {
		s.SetLoginTime(v)
	})
}

// UpdateLoginTime sets the "login_time" field to the value that was provided on create.
func (u *UserLoginUpsertBulk) UpdateLoginTime() *UserLoginUpsertBulk {
	return u.Update(func(s *UserLoginUpsert) {
		s.UpdateLoginTime()
	})
}

// Exec executes the query.
func (u *UserLoginUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserLoginCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserLoginCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserLoginUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
