// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DailyUniqueUser is the predicate function for dailyuniqueuser builders.
type DailyUniqueUser func(*sql.Selector)

// MonthlyUniqueUser is the predicate function for monthlyuniqueuser builders.
type MonthlyUniqueUser func(*sql.Selector)

// UserLogin is the predicate function for userlogin builders.
type UserLogin func(*sql.Selector)
